### PR TITLE
feat(docs): implement swagger in documents and evidences controllers

### LINKED ISSUE #43: feat(docs): implement Swagger in documents and evidences

### PR DESCRIPTION
**Pull request by wendoxx**

### CODE REVIEW

**Comment by wendoxx** [comment]
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

Issue Number: N/A

## PR Type

What kind of change does this PR introduce?



- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior? (Optional)



## What is the new behavior?
Added documentation for the Documents and Evidences controllers, with their endpoints documented using Swagger v3.


## Other information (Optional)
Screenshot from 2024-06-01 00-46-01
Screenshot from 2024-06-01 00-46-08

**Review by AllanPeterson — APPROVED** [review]
LGTM.

**Review by hax1zi — APPROVED** [review]
LGTM

**Review by rafael-dev2021 — APPROVED** [review]
LGTM

**Pull request merged**
