### PR TITLE
feat: documents and evicence

### LINKED ISSUE #12: feat: create Documents and Evidences

### PR DESCRIPTION
**Pull request by wendoxx**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

Issue Number: #12 

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the new behavior?
Added DocumentsAndEvidence controller and endpoints. Package 'controller' was renamed to 'controllers'

### CODE REVIEW

**Comment by wendoxx** [comment]
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

Issue Number: #12 

## PR Type

What kind of change does this PR introduce?



- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:




## What is the new behavior?
Now, the controller is complete. All packages and classes have been added, and the application is working.



## Other information (Optional)

**Comment by wendoxx** [comment]
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

Issue Number: #12 

## PR Type

What kind of change does this PR introduce?



- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:




## What is the new behavior?
Now the controller is complete, with all its endpoints. All packages and classes have been added, the application is working, and all conflicts have been resolved.



## Other information (Optional)
Screenshot from 2024-05-17 16-50-20
Screenshot from 2024-05-17 16-50-23

**Review by hax1zi — APPROVED** [review]
LGMT

**Review by AllanPeterson — COMMENTED** [review]
LGTM.

**Review by AllanPeterson — APPROVED** [review]
LGTM

**Review by ygorsimoes — APPROVED** [review]
As this is a new feature, there are not many considerations to consider. There will probably be improvements soon.

**Pull request merged**
